# Generated by Django 5.2.2 on 2025-06-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique identifier for the student', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject (e.g., Mathematics, Science)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the subject (e.g., MATH101)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('activity', 'Activity'), ('quiz', 'Quiz'), ('exam', 'Exam')], help_text='Type of assessment (Activity, Quiz, Exam)', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, help_text='Score obtained (e.g., 85.50)', max_digits=5)),
                ('date_recorded', models.DateField(auto_now_add=True, help_text='Date the grade was recorded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the grade', null=True)),
                ('student', models.ForeignKey(help_text='The student who received this grade', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('subject', models.ForeignKey(help_text='The subject for which the grade was given', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.subject')),
            ],
            options={
                'ordering': ['student', 'subject', 'date_recorded', 'grade_type'],
                'unique_together': {('student', 'subject', 'grade_type', 'date_recorded')},
            },
        ),
    ]
