# students/urls.py
# URL routing for the 'students' app's API endpoints.

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import all necessary ViewSets
from .views import StudentViewSet, SubjectViewSet, PaperViewSet, GradeViewSet

# Initialize a DefaultRouter instance
router = DefaultRouter()

# Register ViewSets with the router.
# The router automatically generates URL patterns for list, create, retrieve, update, and delete actions.
router.register(r'students', StudentViewSet, basename='student')
router.register(r'subjects', SubjectViewSet, basename='subject')
router.register(r'papers', PaperViewSet, basename='paper') # Endpoint for Paper model
router.register(r'grades', GradeViewSet, basename='grade')

# The API URLs are now automatically determined by the router.
# This pattern includes all URLs generated by the registered viewsets.
urlpatterns = [
    path('', include(router.urls)),
]

